agent_id: "152050db-bac5-4c9c-9afc-b2314f4394d7"
cert_dir: ../config
command_timeout: 300
heartbeat_interval: 60
log_level: INFO
manager_host: localhost
manager_port: 8001
manager_ws_port: 8001
reconnect_interval: 30
scan_paths:
- C:\
